version: '3.8'

services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  nestjs-api:
    image: nestjs-api
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: npm run start:debug
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge