version: '3.8'

services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - api/.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - api/.env

  nestjs-api:
    image: nestjs-api
    build:
      context: ./api
      dockerfile: ../docker/node/Dockerfile
    command: npm run start:debug
    env_file:
      - api/.env
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

  ionic-front:
    image: ionic-front
    build:
      context: ./front
      dockerfile: ../docker/front/Dockerfile
    command: npm run start
    env_file:
      - front/.env
    volumes:
      - ./front:/usr/src/app
    ports:
      - "4200:4200"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge